---
- hosts: webservers
  become: yes
  
  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started

- hosts: dbservers
  become: yes

  tasks: 
  - name: Ensure that MySQL is installed
    yum: name=mariadb state=present
 
  - name: Start MySQL services
    service: name=mariadb enabled=yes state=started

- hosts: webservers:dbservers
  become: yes

  tasks:
  - name: Stop IPtables
    service: name=iptables enabled=no state=stoped
